
# version: 2.6.2255
					
#This file is automatically generated. Do not remove or change
@CLASS				
xcontrols				
@OPTIONS				
static				
partial				
@auto[]				
^rem{				
15.12.2015 
11:36
}					
@getVersion[]			
$version[2.6]			
$revision[2255]			
$result[${version}.${revision}]	
