@echo off
echo SVN Make ver.p script v 1.0.
echo.

	if "%1"=="" (cd ..)
	
	set /p ver=<.version
	TortoiseProc.exe /command:log /path:"%cd%" /closeonend:3 /outfile:"%cd%\.revision" 

	set /p rev=<.revision
	echo Current revision: %rev%
::	del .revision
	
	echo Generating ver.p file...
	
	echo.>ver.p

	echo # version: %ver%.%rev%>>ver.p
	echo.					>>ver.p
	echo #This file is automatically generated. Do not remove or change!>>ver.p
	echo @CLASS				>>ver.p
	echo xcontrols				>>ver.p

	echo @OPTIONS				>>ver.p
	echo static				>>ver.p
	echo partial				>>ver.p


	echo @auto[]				>>ver.p
	echo ^^rem{				>>ver.p

	date/t					>>ver.p
	time/t					>>ver.p

	echo }					>>ver.p

	echo @getVersion[]			>>ver.p
	echo $version[%ver%]			>>ver.p
	echo $revision[%rev%]			>>ver.p
	echo $result[${version}.${revision}]	>>ver.p
	
	echo Done

	if "%1"=="" (cd .\.bat)
	
pause
